const mapAvailabilityStatuses = {
  "On Shelf": [
    "Offsite Available",
    "Regular loan",
    "Video",
    "Library use only",
    "Microform",
    "Multi-Media",
    "Periodicals",
    "Reference",
    "Recorded music",
    "Juvenile",
    "Leisure",
    "Special",
    "Spoken Word",
    "In house loan",
    "Special Collection",
    "US documents",
    "International documents",
    "Reserve 2 hour loan",
    "Reserve 4 hour loan",
    "Reserve 6 hour loan",
    "Reserve 24 hour loan",
    "Reserve 3 day loan",
    "Reserve 7 day loan",
    "Reserve 14 day loan",
    "Reserve 3 hour loan",
    "Reserve 2 hour photocopy",
    "Reserve 4 hour loan AFC",
    "ILL",
    "ILL library use only",
    "BLCC Laptop",
    "BLCC Peripherals",
    "Hourly loan",
    "EZ Borrow item",
    "BTECH",
    "BMICR",
    "NYU GREY ART",
    "REF6NYCENSUS",
    "NYAA",
    "NYACADART",
    "INET1",
    "BMEZZ",
    "CD Rom",
    "NO ITEM STATUS"
  ]
}
