version: "3.7"
x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./spec:/app/spec
    - ./package.json:/app/package.json
    - ./testem.json:/app/testem.json
    - ./webpack.config.js:/app/webpack.config.js
    - ./yarn.lock:/app/yarn.lock

services:
  webpack-build:
    build: .
    image: nyulibraries/alephjs
    command: yarn run build:prod
    labels:
      - 'nyulibraries.app=aleph_js_assets'
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - dist-volume:/app/dist
    # <<: *default-volumes
  
  webpack-watch:
    build: .
    image: nyulibraries/alephjs
    command: yarn build:dev:watch
    # <<: *default-volumes

  test:
    build:
      context: .
      shm_size: 1G
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    image: nyulibraries/alephjs
    command: ["yarn", "run", "test"]
    ports: 
      - 7357:7357
    volumes:
      - dist-volume:/app/dist
    # <<: *default-volumes

  yarn:
    image: node:8
    working_dir: /app
    entrypoint: ["yarn"]
    volumes:
      - ./:/app

volumes:
  dist-volume:
