version: "3.7"
x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./spec:/app/spec
    - ./package.json:/app/package.json
    - ./testem.json:/app/testem.json
    - ./webpack.config.js:/app/webpack.config.js

services:
  webpack-build:
    build: .
    image: nyulibraries/alephjs
    command: yarn run build:prod
    labels:
      - 'nyulibraries.app=aleph_js_assets'
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    # <<: *default-volumes
  
  webpack-watch:
    build: .
    image: nyulibraries/alephjs
    command: yarn build:dev:watch
    # <<: *default-volumes

  test:
    build:
      context: .
      shm_size: 1G
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    image: nyulibraries/alephjs
    command: ["yarn", "run", "test"]
    ports: 
      - 7357:7357
    depends_on: 
      - webpack-build
    # <<: *default-volumes
