version: "3"
services:
  deploy_s3_production:
    build: .
    volumes:
      - ./js/dist:/app/js/dist
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    command: aws s3 sync js/dist s3://cdn.library.nyu.edu/aleph --exclude "*" --include "application.min.js" --delete

  deploy_s3_dev:
    build: .
    volumes:
      - ./js/dist:/app/js/dist
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    command: aws s3 sync js/dist s3://dev.cdn.library.nyu.edu/aleph --exclude "*" --include "application.min.js" --delete

  test:
    build: .
    volumes:
      - ./js/dist:/app/js/dist
    command: npm run test
