docker-defaults: &docker-defaults
  docker:
    - image: docker:18.03.0-ce-git
  working_directory: ~/app

dc-setup: &dc-setup
  run:
    name: Setup docker-compose dependency
    command: |
      apk add --no-cache python3
      pip3 install docker-compose==1.20.1

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - run:
          name: Build and cache containers
          command: |
            docker-compose build
            mkdir -p docker-cache
            docker save -o docker-cache/aleph_js_deploy_dev.tar nyulibraries/aleph_js_deploy_dev
            docker save -o docker-cache/aleph_js_deploy_production.tar nyulibraries/aleph_js_deploy_production
      - run:
          name: Test
          command: docker-compose run test
      - save_cache:
          key: docker_cache
          paths:
            - docker-cache

  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *dc-setup
      - restore_cache:
          key: docker_cache
      - run:
          name: Get cached dev deploy image
          command: |
            docker load < docker-cache/aleph_js_deploy_dev.tar
      - run:
          name: Deploying to development S3
          command: |
            AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV docker-compose run deploy_s3_dev

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *dc-setup
      - restore_cache:
          key: docker_cache
      - run:
          name: Get cached dev deploy image
          command: |
            docker load < docker-cache/aleph_js_deploy_production.tar
      - run:
          name: Deploying to production S3
          command: |
            AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY docker-compose run deploy_s3_production

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
