version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/aleph_js
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container and run tests
          command: |
            docker-compose run test

      - deploy:
          name: Deploy
          command: |
            echo "Deploying to S3"
            aws s3 sync js/dist s3://cdn.library.nyu.edu/aleph --exclude "*" --include "application.min.js" --delete
