version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/aleph_js
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container and run tests
          command: |
            docker-compose run test

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploying to production S3"
              docker-compose run deploy_s3_production
            else; then
              echo "Deploying to development S3"
              docker-compose run deploy_s3_dev
            fi
